#define BI_VERSION_ID 50123
#define BI_VERSION "Grace-5.1.23"
#define BI_GUI "@(#)Motif Version 2.2.2i (2.1.32)"
#define BI_GUI_XBAE "4007"
#define BI_T1LIB "1.3.1p3-grace"
#define BI_PNGLIB ""
#define BI_LIBJPEG ""
#define BI_LIBPDF ""
#define BI_CCOMPILER "gcc -O2  -fno-common -Wall -Wpointer-arith -Wnested-externs -I.. -I. -I../T1lib/t1lib -I../Xbae -I/usr/OpenMotif/include -I/usr/local/fftw-3.3.4/include -I/usr/X11/include -L/usr/OpenMotif/lib -L/usr/local/fftw-3.3.4/lib  -L/usr/X11/lib   ../Xbae/Xbae/libXbae.a -lXm -lXpm -lXp -lXmu -lXt -lXext -lX11  -lSM -lICE  ../cephes/libcephes.a   ../T1lib/libt1.a    -lz -lm  "
#define BI_SYSTEM "Darwin Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 14.1.0 x86_64"
#define BI_DATE "Mon Mar  2 15:08:18 2015"

#define GRACE_HOME "/usr/local/grace"
#define GRACE_EDITOR "xterm -e vi"
#define GRACE_PRINT_CMD "lp -c"
#define GRACE_HELPVIEWER "mozilla %s"
